# Visualizing .obj

In [10]:
import numpy as np 

def load_obj(file_path):
    "Get Vertices and triangles from a .obj file"
    vertices = []
    faces = []

    with open(file_path, 'r') as f:
        for line in f:
            if line.startswith('v '):  # vertex
                parts = line.strip().split()
                v = list(map(float, parts[1:4]))
                vertices.append(v)

            elif line.startswith('f '):  # face
                parts = line.strip().split()
                
                # f 1 2 3  veya  f 1/1/1 2/2/2 3/3/3
                face = []
                for p in parts[1:]:
                    idx = p.split('/')[0]  # sadece vertex index al
                    face.append(int(idx) - 1)  # obj 1-based → 0-based

                faces.append(face)

    return np.array(vertices), np.array(faces)


In [15]:
file_path = "source_obj/cat-poses/cat-01.obj"
v,f = load_obj(file_path=file_path)
v.shape, f.shape

((7207, 3), (14410, 3))

In [ ]:
f[:2]

array([[7206,    0,    1],
       [7206,    1,    2]])

: 

In [27]:
print(f[:3])
print(v[f[:3]])

[[7206    0    1]
 [7206    1    2]
 [   3    4    5]]
[[[ 0.024752  0.002891 -0.132067]
  [ 0.014956  0.002568 -0.129692]
  [ 0.012093  0.014048 -0.141544]]

 [[ 0.024752  0.002891 -0.132067]
  [ 0.012093  0.014048 -0.141544]
  [ 0.022231  0.014703 -0.144126]]

 [[ 0.062614  0.041084 -0.117841]
  [ 0.060695  0.055652 -0.126856]
  [ 0.063395  0.064455 -0.114805]]]
